-- First, create the Department table (parent table)
CREATE TABLE IF NOT EXISTS department (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_code VARCHAR(10) NOT NULL UNIQUE,
    department_name VARCHAR(50) NOT NULL,
    location VARCHAR(100),
    manager_id INT,
    active BOOLEAN DEFAULT true,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_date TIMESTAMP
);

-- Then, modify the Employee table to include the department reference
CREATE TABLE IF NOT EXISTS employee (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    department_id INT,
    CONSTRAINT fk_employee_department
        FOREIGN KEY (department_id)
        REFERENCES department(id)
);

-- Add the manager reference to department after employee table is created
ALTER TABLE department
ADD CONSTRAINT fk_department_manager
    FOREIGN KEY (manager_id)
    REFERENCES employee(id);
